-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce`;

CREATE SCHEMA `full-stack-ecommerce`;
USE `full-stack-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Chocolate Candy');
INSERT INTO product_category(category_name) VALUES ('Gummy Candy');
INSERT INTO product_category(category_name) VALUES ('Lollipop Candy');
INSERT INTO product_category(category_name) VALUES ('Mints Candy');

-- -----------------------------------------------------
-- Chocolate Candy
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1000', 'Snickers', 'A chocolate bar filled with nougat, peanuts, and caramel. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1000.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1001', 'Kit Kat', 'A chocolate-covered wafer candy that can be easily split into individual pieces. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1001.png', 1, 100, 20.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1002', 'Hershey\'s Milk Chocolate', 'A classic chocolate bar made with milk chocolate. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1002.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1003', 'Milky Way', 'A chocolate bar filled with nougat and caramel. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1003.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1004', 'Twix', 'A chocolate-covered cookie bar with a layer of caramel. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1004.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1005', 'M&Ms', 'Colorful candy shells filled with milk chocolate. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1005.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1006', 'Reese\'s Peanut Butter Cups', 'A cup-shaped candy with a peanut butter filling covered in chocolate. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1006.png', 1, 100, 14.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1007', 'Cadbury Dairy Milk', 'A creamy milk chocolate bar. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1007.png', 1, 100, 16.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1008', 'Lindt Lindor Truffles', 'Round chocolate truffles with a smooth filling. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1008.png', 1, 100, 25.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1009', 'Ferrero Rocher', 'A chocolate-covered hazelnut candy with a crispy wafer inside. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1009.png', 1, 100, 23.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1010', 'Toblerone', 'A triangular-shaped chocolate bar with nougat and almonds. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1010.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1011', '3 Musketeers', 'A chocolate bar filled with whipped nougat. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1011.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1012', 'Godiva Chocolates', 'Premium chocolates in a variety of flavors and truffle fillings. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1012.png', 1, 100, 24.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1013', 'Nestle Crunch', 'A chocolate bar with crisped rice mixed in. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1013.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1014', 'Ghirardelli Chocolate Squares', 'Square-shaped chocolates with a variety of fillings, such as caramel or mint. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1014.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1015', 'Dove Chocolate', 'Smooth and creamy chocolate in a variety of forms, such as bars or bite-sized pieces. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1015.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1016', 'Baby Ruth', 'A chocolate-covered candy bar with peanuts, caramel, and nougat. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1016.png', 1, 100, 27.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1017', 'Milkybar', 'A white chocolate bar. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1017.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1018', '100 Grand', 'A candy bar filled with crispy rice and caramel covered in milk chocolate. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1018.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1019', 'Maltesers', 'A chocolate-covered malt ball candy. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1019.png', 1, 100, 13.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1020', 'Lindt Excellence Dark Chocolate', 'A premium dark chocolate bar. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1020.png', 1, 100, 19.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1021', 'Rolo', 'A caramel-filled chocolate candy in a roll shape. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1021.png', 1, 100, 18.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1022', 'Andes Mints', 'Small rectangular chocolates with a mint filling. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1022.png', 1, 100, 26.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1023', 'Toblerone Dark Chocolate', 'A dark chocolate version of the classic Toblerone bar. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1023.png', 1, 100, 22.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('CHOCOLATE-CANDY-1024', 'Aero', 'A chocolate bar with a bubbly, aerated center. Buy it now!', 'assets/images/products/chocolatecandy/chocolatecandy-1024.png', 1, 100, 16.99, 1, NOW());

-- -----------------------------------------------------
-- Gummy Candy
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1000', 'Gummy Bears', 'Classic bear-shaped gummy candy in a variety of fruity flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1000.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1001', 'Sour Patch Kids', 'Chewy candy with a sour sugar coating in a variety of fruit flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1001.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1002', 'Swedish Fish', 'Soft and chewy fish-shaped candy with a fruity flavor. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1002.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1003', 'Haribo Goldbears', 'Another classic bear-shaped gummy candy in a variety of fruity flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1003.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1004', 'Trolli Sour Brite Crawlers', 'Gummy worms coated in sour sugar. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1004.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1005', 'Black Forest Organic Gummy Bears', 'Organic gummy bears made with real fruit juice. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1005.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1006', 'Mike and Ike', 'Fruit-flavored chewy candy in a variety of shapes, including oblong and round. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1006.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1007', 'Hi-Chew', 'Japanese gummy candy with a chewy texture and a fruity flavor. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1007.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1008', 'Juicy Drop Gummies', 'Gummies with a sour gel that can be squeezed onto the candy for extra flavor. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1008.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1009', 'Jujubes', 'Small, chewy candy in a variety of fruit flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1009.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1010', 'Jolly Rancher Gummies', 'Gummies in a variety of fruity flavors inspired by the classic hard candy. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1010.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1011', 'Welch\'s Fruit Snacks', 'Fruit-shaped gummies made with real fruit juice. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1011.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1012', 'Albanese Gummi Worms', 'Colorful, worm-shaped gummies in a variety of fruity flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1012.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1013', 'SweeTarts Soft and Chewy Ropes', 'Soft and chewy candy ropes in a variety of flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1013.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1014', 'Brach\'s Gummy Bears and Worms', 'A mix of classic gummy bears and worms in a variety of flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1014.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1015', 'Starburst Gummies', 'Gummies with the same fruity flavors as the classic Starburst candy. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1015.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1016', 'Razzles', 'A unique candy that starts as a fruit-flavored gum and turns into a chewy candy. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1016.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1017', 'Nerds Gummy Clusters', 'A combination of gummies and crunchy Nerds candy. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1017.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1018', 'Airheads Xtreme Sour Belts', 'Sour gummy candy belts in a variety of flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1018.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1019', 'Jelly Belly Sours', 'Jelly beans with a sour sugar coating in a variety of flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1019.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1020', 'Fun Dip Gummies', 'Gummies in the same fruity flavors as the classic Fun Dip candy. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1020.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1021', 'Skittles Chewies', 'Soft and chewy versions of the classic Skittles candy. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1021.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1022', 'Sour Punch Straws', 'Sour gummy candy straws in a variety of fruit flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1022.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1023', 'Dots', 'Small, round gummy candy in a variety of fruit flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1023.png', 1, 100, 18.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GUMMYCANDY-1024', 'Mike and Ike Mega Mix', 'A mix of chewy candy in a variety of shapes and fruit flavors. Buy it now!', 'assets/images/products/gummycandy/gummycandy-1024.png', 1, 100, 18.99, 2, NOW());

-- -----------------------------------------------------
-- Lollipop Candy
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1000', 'Blow Pops', 'A hard candy shell with a gum-filled center in a variety of fruit flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1000.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1001', 'Dum Dums', 'Small, round lollipops in a variety of flavors, including cream soda and cotton candy. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1001.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1002', 'Chupa Chups', 'A popular Spanish lollipop with a variety of flavors and designs. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1002.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1003', 'Tootsie Pops', 'A hard candy shell with a chewy chocolate center in a variety of fruit flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1003.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1004', 'Ring Pops', 'A lollipop shaped like a ring with a hard candy top and a fruity, chewy bottom. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1004.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1005', 'Charms Fluffy Stuff Cotton Candy Pops', 'A lollipop shaped like a fluffy ball of cotton candy. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1005.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1006', 'Jolly Rancher Lollipops', 'A hard candy lollipop in a variety of fruit flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1006.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1007', 'Saf-T-Pops', 'A lollipop with a looped handle that is safe for young children. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1007.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1008', 'Candy Cane Lollipops', 'A holiday-themed lollipop shaped like a traditional candy cane. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1008.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1009', 'Warheads Sour Pops', 'A sour hard candy lollipop in a variety of flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1009.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1010', 'Smarties Pops', 'A lollipop with a hard candy shell in a variety of fruit flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1010.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1011', 'Tootsie Roll Pops', 'A hard candy shell with a chewy Tootsie Roll center in a variety of fruit flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1011.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1012', 'Melville Candy Company Large Swirl Lollipop', 'A large, colorful lollipop with a swirled design. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1012.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1013', 'Pop Rocks Dips', 'A lollipop with a dipping powder that creates popping candy in your mouth. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1013.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1014', 'Creamsicle Lollipops', 'A lollipop with a creamy orange and vanilla flavor, reminiscent of the classic ice cream treat. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1014.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1015', 'Push Pops', 'A lollipop with a hard candy top and a push-up, fruity gel center. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1015.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1016', 'Haribo Happy Cola Bottles Lollipops', 'A lollipop in the shape of a cola bottle with a cola flavor. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1016.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1017', 'Taffy Town Lollipops', 'A lollipop with a creamy taffy center in a variety of flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1017.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1018', 'Crazy Candy Factory Giant Gumball Lollipops', 'A large lollipop with a gum-filled center. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1018.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1019', 'Jelly Belly Lollipops', 'A lollipop with a hard candy shell in a variety of Jelly Belly jelly bean flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1019.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1020', 'M&Ms Lollipops', 'A lollipop with a hard candy shell and an M&M candy in the center. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1020.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1021', 'YumEarth Organic Pops', 'An organic lollipop in a variety of fruity flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1021.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1022', 'Fun Dip Lollipops', 'A lollipop with a hard candy top and a dipping stick to dip into a flavored powder. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1022.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1023', 'Sour Patch Kids Lollipops', 'A lollipop with a sour candy coating in a variety of fruit flavors. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1023.png', 1, 100, 17.99, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('LOLLIPOPCANDY-1024', 'Goetze\'s Cow Tales Mini Pops', 'A lollipop with a creamy caramel flavor reminiscent of a classic Cow Tale candy. Buy it now!', 'assets/images/products/lollipopcandy/lollipopcandy-1024.png', 1, 100, 17.99, 3, NOW());

-- -----------------------------------------------------
-- Mints Candy
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1000', 'Altoids', 'Small, curiously strong mints in a variety of flavors. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1000.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1001', 'Peppermint Patties', 'Thin, round chocolate discs filled with a creamy peppermint filling. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1001.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1002', 'Tic Tac', 'Small, oval-shaped mints in a variety of flavors. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1002.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1003', 'Mentos', 'Chewy mint candies with a hard shell. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1003.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1004', 'Junior Mints', 'Small, round chocolate discs filled with a creamy peppermint filling. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1004.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1005', 'York Peppermint Patties', 'Thin, round chocolate discs filled with a cool peppermint filling. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1005.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1006', 'Ice Breakers Mints', 'Small, round mints with a cooling sensation. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1006.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1007', 'Lifesavers Wint-O-Green', 'Small, round mints with a cool wintergreen flavor. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1007.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1008', 'Andes Mints', 'Small, rectangular chocolate candies filled with a creamy mint filling. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1008.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1009', 'Altoids Smalls', 'Miniature version of Altoids, still with a strong minty flavor. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1009.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1010', 'Eclipse Mints', 'Small, oval-shaped mints with a cool, refreshing flavor. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1010.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1011', 'Polo Mints', 'Round, flat mints with a hole in the center, in a variety of flavors. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1011.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1012', 'After Eight Mints', 'Thin, square chocolate pieces filled with a creamy mint filling. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1012.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1013', 'Fisherman\'s Friend', 'Strong, menthol-flavored lozenges designed to soothe sore throats. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1013.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1014', 'Halls Menthol Drops', 'Menthol-flavored cough drops. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1014.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1015', 'Ice Chips Candy', 'Small, hard candies with a cooling mint flavor. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1015.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1016', 'King Mints', 'Large, round mints with a cooling sensation. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1016.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1017', 'Necco Wafers Wintergreen', 'Small, round wafers with a refreshing wintergreen flavor. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1017.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1018', 'Pearson\'s Mint Patties', 'Soft, chewy mint candies coated in dark chocolate. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1018.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1019', 'Ricolino Mentos', 'Chewy mint candies with a hard shell, similar to the Mentos brand. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1019.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1020', 'Smith Brothers Cough Drops', 'Menthol-flavored cough drops with a storied history. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1020.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1021', 'St. Claire\'s Organics Mints', 'Organic, vegan, and gluten-free mints in a variety of flavors. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1021.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1022', 'Starbucks Peppermint Syrup', 'A syrup used to add peppermint flavor to coffee, hot chocolate, and other beverages. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1022.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1023', 'Willy Wonka Everlasting Gobstopper Snowballs', 'Small, round candies that change color and flavor as they are eaten, with a cool minty flavor in the center. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1023.png', 1, 100, 16.99, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('MINTSCANDY-1024', 'Wrigley\'s Doublemint Gum', 'Gum with a cool, refreshing mint flavor. Buy it now!', 'assets/images/products/mintscandy/mintscandy-1024.png', 1, 100, 16.99, 4, NOW());

